# ~/.config/starship.toml

# Use custom format
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$custom
$all
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Add the blank line at the start of the prompt
add_newline = true


[directory]
disabled = false
truncate_to_repo = true
truncation_length = 8  # number of parent dirs
fish_style_pwd_dir_length = 3
truncation_symbol = "\u001b[1;33m…/\u001b[0;96m"
read_only = " [RO]"

[directory.substitutions]
"/" = "\u001b[1;33m/\u001b[0;96m"


[custom.cwd]
disabled = true
# command = """ echo "$PWD" | sed -e "s!$HOME!~!" | sed "s/\\//$(printf "\\033[1;33m\\/\\033[0;37m")/g" """
command = """ echo -n "$PWD" | sed -e "s!$HOME!~!" | sed -re "s!([^/]{3})[^/]{3,}+/!\\1…/!g" | sed "s/\\//$(printf "\\033[1;33m\\/\\033[0;37m")/g" """
when = "true"
shell = ["sh"]

#directories = ["emareg", "Dokumente"]
#command = """ echo "$PWD" | sed "s/\\//$(printf "\\033[1;33m\\/\\033[0;37m")/g" """
#format = " transcending [$output]($style)"

